src/gpio.rs

You need to set the output enable bit of gpio_cfgctl34 in order for a GPIO to function as output.
This is specified in the reference manual, with no register information.
Digging through the C SDK I found the Output Enable function and it only sets/clears this bit, so this should be sufficient

Enable OE bit when setting pin output, and clear it when setting input

---

Cargo.toml
src/delay.rs
src/gpio.rs
src/lib.rs

Needed some delay functions to initialise peripherals correctly, so I've ported some of the functions from
https://github.com/gd32v-rust/gd32vf103-hal/blob/master/src/delay.rs
There's a few changes to them due to newer version of embedded-hal.
Fixed up bug when allocating GPIO to UART that was overwriting adjacent pins, breaking JTAG.
Added some missing UART->GPIO muxing impls so that
https://github.com/sipeed/bl602-rust-guide/blob/main/src/main.rs
will run.

Uart fixes and delay code brought over from gd32vf103-hal

---

Cargo.toml
src/clock.rs

I've ported some of the core clock initialization code from 
https://github.com/pine64/bl_iot_sdk and 
https://github.com/bouffalolab/bl_iot_sdk
Only the Strict API for clocks has been implemented. Still not 100% happy with the names in the API for Freeze, but they reasonably consistent with other HALs.
The private functions that implement the separate phases of initialization still have the same names as those in the SDK repos mentioned above. This was to make it easier to do side-by-side comparison to verify that they were functionally identical - this may help with review as well.
You can spin up the PLL independently of using it as the system clock, but if it's enabled it always gets used as the UART clock source.
I have tested the UART at a few frequencies while using different …

Core clock initialization

---

Cargo.toml

Cargo still uses the relative path for the `bl602-pac` dependency, which I assume is from when the repository was private.
This changes that by using the public git repository instead.

Use public bl602-pac repository for dependency

---

src/gpio.rs

The `paste` proc macro appears to handle fn implementations when they're wrapped.
Closes #7

Fix proc macro expansion error when Rust < 1.45

---

.github/workflows/ci.yml
.github/workflows/clippy.yml

This adds workflows for Github Actions with 2 workflows:
* **ci**: Runs `cargo check` on Rust `stable`, `nightly`, and our MSRV (`1.42.0`)
* **clippy**: runs `cargo clippy` on Rust stable
This is currently blocked by ~#6~ and #8

Add Github Actions CI workflows

---

src/checksum.rs
src/lib.rs

This PR adds an abstraction around the `CKS` peripheral that lets the user compute checksums in hardware.
This could be made faster with a DMA implementation later on.
Currently blocked by sipeed/bl602-pac#3

Add checksum engine abstraction

---

src/clock.rs

There was a few issues making the clock code in the HAL broken/unusable.
The first is that due to an address calculation error, I was calling RomDriver_DelayMS instead of RomDriver_PDS_Power_On_PLL, so the PLL was not coming up correctly.
I also didn't specify that the function had a return value, so we would have been leaving it's return value on the stack...
The second is that I tried to fall back to 32MHz for the UART peripheral clock if no UART clock was given.
This failed for the blinky example code, since it couldn't find a valid integer divisor in the Strict configurator.
We now fall-back to the UART peripheral clock source for the UART clock, which should always be achievable. (divider = 1)
Thirdly, removed a PLL frequency that's not possible for the System Clock to use from the …

Fix PLL init & UART default clock, remove invalid PLL setting

---

src/serial.rs

Original code used integer divide to get closest divider for UART baud.
This is fine if you pick something that divides cleanly into UART clock, but otherwise 
it can be off by a decent amount.
Switch to floating point + add 0.5 at the end to provide equivalent to rounding to nearest integer.
This improves worst case baud clock selection.
Also, added a check for a request for baud rate > UART clock, since we could not possibly provide that

Round UART baud instead of floor

---

src/serial.rs

try_write is supposed to return nb::Error::WouldBlock if it's not possible to write, but it was ignoring errors.
This PR changes it to return nb::Error::WouldBlock when the FIFO is full.
try_flush isn't very documented, but my intuition is that it's supposed to return nb::Error::WouldBlock until everything that was previously written has been fully transmitted (so you can safely turn off the UART peripheral, reset the device, etc)
My first attempt just checked if the FIFO had any data in it, but this would return Ok() when the last byte was still being transmitted.
The current solution is to return nb::Error::WouldBlock if the FIFO has bytes in it or the TX BUSY bit is set

Improve behaviour of uart::try_write and uart::try_flush

---

src/clock.rs
src/gpio.rs
src/lib.rs
src/spi.rs

This adds SPI master functionality. (Only 8 bit transfers for now)
I tested this with a logic analyzer, loop back and an STM32F103 as SPI slave. It actually works so far but the SCLK frequency is half of what I configure - maybe someone sees where that problem is.  
See https://github.com/bjoernQ/bl602-hal/blob/df148c17aed4ad76b7f42f6277a36d3cf3e640e7/src/spi.rs#L140
I was also not able to test with advanced clock settings since my currently only DT-BL10 seems to be somewhat faulty and acts weird in some regards. (More dev boards are ordered but they did not arrive yet)

SPI master implementation

---

src/clock.rs
src/gpio.rs
src/i2c.rs
src/lib.rs

This implements I2C functionality.
- implements Read and Write traits since I don't see how / if the BL602 i2c peripheral can support the contract of Transactional
- supports 7 bit addressing
I tested this with an SSD1306 (just set all pixels on and the display on / off in a loop) and communicating with an BMP180 sensor. Worked for me and looks fine when inspecting the communication with a logic analyzer.

Implement I2C

---

src/i2c.rs
src/timer.rs

While migrating to new the new PAC, a few registers were flagged as invalid for modify access as the registers are Write Only.
Writing i2c_fifo_wdata has the same behavior as previous to this PR. The register is 32bits wide, we were writing 32bits and ignoring read value
The interrupt clear registers auto-clear as far as I can tell via the Reference Manual, so we should not need to manually preserve their contents
Attached are snippets of RM 1.2 for verifying these changes

Replace reg.modify() with reg.write() on WO registers

---

src/i2c.rs

This hopefully fixes #23 
Before it used _cr_i2c_bus_busy_clr_ to wait for the transfer to finish which is wrong.

Use sts_i2c_bus_busy not cr_i2c_bus_busy_clr

---

.cargo/config.toml
.vscode/settings.json
Cargo.toml
examples/rtc.rs
src/lib.rs
src/rtc.rs

This adds a simple implementation of the RTC peripheral as found in https://github.com/bouffalolab/bl_iot_sdk/blob/90acb7b46d11343d27db9518c4f86d94572c6629/components/hal_drv/bl602_hal/bl_rtc.c
The clock seems to drift a bit but it's usable as a monotonic timestamp at least.
Additionally, I added a `.vscode/settings.json` file to prevent VSCode with rust-analyzer to always show an error in lib.rs
Last not least it updates the `embedded-time`  dependency to `0.12.0`

Implement RTC

---

Cargo.toml

Since we didn't have the version pinned new users get alpha.5
Pin to alpha.4 until we've upgraded to the new traits.

Pin to previous EH alpha to fix builds

---

Cargo.toml
examples/blinky.rs
examples/i2c_ssd1306.rs
examples/led_interrupt_switch.rs
examples/rtc.rs
examples/serial.rs
src/clock.rs
src/delay.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/rtc.rs
src/serial.rs
src/spi.rs
src/timer.rs

Lots of little changes to bring us over to alpha5.
The biggest change is the lack of Default impls for some traits in SPI.
I implemented the GPIO toggle trait manually, as I figure that's going to be commonly used.
I also renamed the i2c, rtc and spi constructors to be called new() because clippy complained and calling hal::i2c::I2c::i2c() feels pretty silly. That was the last change, and I can back it out if it is too much.

Migrate to embedded-hal 1.0.0-alpha5

---

Cargo.toml

This is the follow up to the ```bl602-pac``` update to allow hard floats by updating to ```riscv 0.7.0```. I have left the riscv-rt version at 0.8.0 as suggested by @9names; letting semver take care of finding the newest release now that it is published.

Version update riscv to support hard floats

---

Cargo.toml

Only affects example builds. Previous versions encounter a lld error fixed in more recent stable. Skip v0.10 as has been yanked.
Fixes #41

Bump riscv-rt to v0.11.0

---

.github/workflows/ci.yml
Cargo.toml
README.md
examples/led_timer_interrupt.rs
examples/watchdog_example.rs

Uses `riscv`'s `critical-section` impl.
We need this it use newer versions of svd2rust anyway.
The examples weren't building for me without it.
Merge #42 first

Use critical-section instead of bare-metal

---

Cargo.toml
build.rs
examples/rtc.rs
examples/serial.rs
examples/watchdog_example.rs
src/clock.rs
src/i2c.rs
src/serial.rs
src/watchdog.rs

This PR makes the changes required by the PAC updates in sipeed/bl602-pac#15 and sipeed/bl602-pac#16.
The `serial` module can new be used with both `UART0` and `UART1` by making the UART generic
with bound `Deref<Target = pac::uart0::RegisterBlock>`.
Additionally, I felt like it might be better practice to not unconditionally enable the `critical-section-single-hart` feature of the `riscv` crate, so I create a new feature for this crate to enable it + made it a default feature.
Any suggestions for improvements are welcome.

Updates for new PAC

---

Cargo.toml
examples/blinky.rs
examples/led_interrupt_switch.rs
examples/led_timer_interrupt.rs
examples/serial.rs
examples/watchdog_example.rs
src/clock.rs
src/delay.rs
src/gpio.rs
src/i2c.rs
src/serial.rs
src/spi.rs
src/timer.rs
src/watchdog.rs

Update all drivers to use embedded-hal 1.0 alpha 11 where possible.
Port all nb drivers to use embedded-hal-nb 1.0 alpha 3.
Move any remaining drivers using removed embedded-hal 1.0 alpha traits to embedded-hal 0.2 traits.
Update the examples to make them build again after all of the above.
Notes:
- examples still have warnings
- i2c transactional is new and untested
- i have not run any of the examples to ensure there is no new breakage
Wait until testing is complete before merging, but you can review at any time.
Please squash this PR when merging.

Update embedded-hal traits

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/clock.rs
src/delay.rs
src/gpio.rs

Just a few changes between rc1 and rc3.
DelayUs is replaced with DelayNs (which has default impls for DelayMs and DelayUs but I've kept the original implementations.
GPIO pin functions now take &mut instead of & to ensure that only one borrower can be active at a time.

embedded-hal 1.0 rc3 updates

---

Cargo.toml
src/delay.rs
src/gpio.rs

Only real difference here is lack of implementation of ToggleableOutputPin, since the default implementation of Toggle for StatefulOutputPin is sufficient/

Update to embedded-hal 1.0 release

---

src/i2c.rs
src/serial.rs
src/spi.rs

Uses the sealed trait pattern from
https://rust-lang.github.io/api-guidelines/future-proofing.html
i2c and spi traits are well constrained already, haven't worked out the correct syntax for serial.
it's probably overkill, since you can't construct a uart without uart pins, and they are already constrained.
[edit]
Decided not to seal uart trait due to above

Use sealed traits instead of unsafe markers on traits

---

src/delay.rs
src/i2c.rs

I2C write was unreliable for a few reasons.
1) timeouts were very short
2) we were only waiting for i2c_bus_busy to be cleared, which sometimes happens before the fifo is empty.
By switching timeouts to use elapsed microseconds (estimated via McycleDelay) and waiting for an empty fifo, I can reliably use a SSD1306 screen now. This was impossible before.
Resolves #48

Fix i2c write
